
// Generated by https://quicktype.io

import { blogApi } from "../../store/blogApi";
import { User } from "../user/userApi";

export interface RegistrationRequest {
    username: string;
    email:    string;
    password: string;
    about_me: string;
}


export const registrationApi = blogApi.injectEndpoints({
    endpoints: (builder) => ({
        registerUser: builder.mutation<User,RegistrationRequest>({
            query: newUser => ({
                url: `/users`,
                method: 'POST',
                body: newUser
            }),
            //transformResponse: (response:User,meta,arg) => {return {...response, avatar_url:response.avatar_url.replace("identicon","robohash")}}
        })
    })
})

export const { useRegisterUserMutation } = registrationApi