// Generated by https://quicktype.io

export interface PostDef {
    author:    Author;
    id:        number;
    text:      string;
    timestamp: string;
    url:       string;
}

export interface Author {
    about_me:     string;
    avatar_url:   string;
    email:        string;
    first_seen:   string;
    has_password: boolean;
    id:           number;
    last_seen:    string;
    posts_url:    string;
    url:          string;
    username:     string;
}

// Generated by https://quicktype.io

export interface Pagin {
    count:  number;
    limit:  number;
    offset: number;
    total:  number;
}

export interface FeedArray {
    data: PostDef[] 
    pagination: Pagin
}