import {blogApi} from '../../store/blogApi'

// Generated by https://quicktype.io

export interface User {
    id:           number;
    url:          string;
    username:     string;
    email:        string;
    has_password: boolean;
    avatar_url:   string;
    about_me:     string;
    first_seen:   string;
    last_seen:    string;
    posts_url:    string;
}


export const userApi = blogApi.injectEndpoints({
    endpoints: (builder) => ({
        getUser: builder.query<User,string>({
            query: (name) => ({url: `/users/${name}`}),
            transformResponse: (response:User,meta,arg) => {return {...response, avatar_url:response.avatar_url.replace("identicon","robohash")}}
        })
    })
})

export const { useGetUserQuery } = userApi